server:
  port: 3003

spring:
  application:
    name: garagem-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mysql}
  jackson:
    serialization:
      write-dates-as-timestamps: false

garage:
  sim:
    base-url: ${GARAGE_SIM_BASE_URL:http://localhost:3000}

logging:
  level:
    org.example: INFO
    io.netty.resolver.dns.DnsServerAddressStreamProviders: OFF

